### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by ghost** [ipld/ipld-yang#1]
Is it this? "YANG is a data modeling language for the definition of data sent over the NETCONF network configuration protocol"

**Comment by hsanjuan** [comment]
Yes, but you need to ask @frankpetrilli for details

**Comment by FrankPetrilli** [comment]
@lgierth, that's the plan. In short, I hope to get yang models implemented in ipld, then modified through interactions with outside protocols in order to modify attributes of the YANG model, then make changes to a network device via Netconf.

**Comment by vmx** [comment]
@FrankPetrilli Can this repository be removed?

**Comment by lanzafame** [comment]
I never knew that this was here but it is a shame we haven't moved forward on this 😢

**Comment by rvagg** [comment]
closing for archival
